apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    environment: non-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
      environment: non-production
  template:
    metadata:
      labels:
        app: my-nginx
        environment: non-production
    spec:
      containers:
      - name: my-nginx
        image: nginx